<?php die( 'These aren\'t the droids you\'re looking for...' );
// extract of translatable text strings from common library classes
__( 'An error was returned while getting update information for %s.', 'wpsso-um' );
__( 'An inconsistency was found in the %1$s update server information &mdash;', 'wpsso-um' );
__( 'Failed saving retrieved update information for %s.', 'wpsso-um' );
__( 'https://developer.wordpress.org/reference/functions/get_plugins/', 'wpsso-um' );
__( 'No plugins defined for updates.', 'wpsso-um' );
__( 'Please note that one or more non-stable / development %s have been selected.', 'wpsso-um' );
__( 'The %1$s plugin (%2$s) version number is missing from the WordPress plugins array.', 'wpsso-um' );
__( 'The <a href="%1$s">WordPress %2$s function</a> is missing and required.', 'wpsso-um' );
__( 'the IPv4 address (%1$s) from the local host does not match the DNS IPv4 address (%2$s).', 'wpsso-um' );
__( 'the update server URL (%1$s) does not appear to be a valid URL.', 'wpsso-um' );
__( 'the update URL provided by the plugin configuration is invalid (%1$s).', 'wpsso-um' );
__( 'the WordPress add_query_arg() function returned an invalid authentication URL (%1$s).', 'wpsso-um' );
__( 'Update checks for %1$s are disabled while this inconsistency persists.', 'wpsso-um' );
__( 'Update error from the WordPress wp_remote_get() function: %s', 'wpsso-um' );
__( 'Update information for %s has been retrieved and saved.', 'wpsso-um' );
__( 'WordPress library file %s is missing and required.', 'wpsso-um' );
_x( 'Update Version Filters', 'metabox title', 'wpsso-um' );
__( 'You may <a href="%1$s">open a new support ticket</a> if you believe this error message is incorrect.', 'wpsso-um' );
